name: CI & CD
on:
    push:
        tags:
            - v*
jobs:
    Build-and-Publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org
                  cache: pnpm
            - uses: browser-actions/setup-chrome@latest

            - name: Install Dependencies
              run: |
                  pnpm i --frozen-lockfile
                  pnpm set-chrome

            - name: Build & Publish
              run: |
                  cd test/  &&  pnpm i  &&  cd ..
                  npm publish --access public --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Update document
              uses: peaceiris/actions-gh-pages@v4
              with:
                  publish_dir: ./docs
                  personal_token: ${{ secrets.GITHUB_TOKEN }}
                  force_orphan: true
